services:
  - type: web
    name: mon-nkama-server
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: uri
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: mon-nkama-client
    env: static
    region: frankfurt
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - path: /api
        destination: http://mon-nkama-server:5000

databases:
  - name: mongodb
    plan: free
    provider: mongodb 